name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Sleep for 5 minutes
        run: |
          Write-Host "Sleeping for 5 minutes..."
          Start-Sleep -Seconds 4000

      - name: Open Chrome Browser
        run: |
          Start-Process "chrome.exe"
          Write-Host "Chrome browser opened"
          Start-Sleep -Seconds 60  # Wait for 1 minute

      - name: Close Chrome Browser
        run: |
          Stop-Process -Name "chrome" -Force
          Write-Host "Chrome browser closed"


       - name: s2f bd
        run: |
          Write-Host "Sleeping for 5 minutes..."
          Start-Sleep -Seconds 4000

